@FinControl.API_HostAddress = http://localhost:5124

GET {{FinControl.API_HostAddress}}/api/categorias

###

POST {{FinControl.API_HostAddress}}/api/categorias
Content-Type: application/json

{
  "nome": "Alimentacao",
  "icone": "fastfood",
  "cor": "#FF5733"
}

